services:
  mysql:
    image: mysql
    container_name: "mysql"
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: car_detailing
      MYSQL_ROOT_PASSWORD: 123